#pragma once
#ifndef UI_H
#define UI_H
#ifdef __cplusplus
extern "C" {
#endif
#define MAX_FILE_NAME 	256
#define MAX_FILES		10

typedef char (*currarr)[MAX_FILE_NAME+1];

typedef struct UI_ UI_;

extern UI_ UI;
#define UI_UP     'w'
#define UI_DOWN   's'
#define UI_SELECT 'e'


struct UI_
{
	/**
	* @brief			Inits the UI
	* @return			Returns 1 if the init was successfull, else 0.
	*/

	unsigned(*init)();
	/**
	* @brief 			Generate an event in the UI
	* @param ev			Event generated by the event generator
	* @return 			Returns 0 if the event was processed, returns ev if the event was not processed.
	*/
	char(*input)(char ev);
	
	char*(*getFile)();
	char*(*getPath)();
	void(*exitFile)();
	currarr  (*getCurrent)(unsigned* sz, unsigned *pos);
	void (*setPos)(int p);
	void(*close)();
};
#ifdef __cplusplus
}
#endif

#endif // !UI_H
